#!/usr/bin/env python
# coding: utf-8

from aktos_dcs import *
import argparse

parser = argparse.ArgumentParser(description='Get configuration values')
parser.add_argument('-i', '--input-file', help='Input configuration file')
parser.add_argument('-k', '--key', default=None, help='key or key tree')

args = parser.parse_args()

config = AktosConfig(args.input_file)
resp = config.get(args.key)
if type(resp) == type({}):
    for k, v in resp.iteritems():
        print k, "\t", v

else:
    print resp