// Generated by LiveScript 1.4.0
var ref$, merge, pack, unpack, mem, out$ = typeof exports != 'undefined' && exports || this;
ref$ = require('aea'), merge = ref$.merge, pack = ref$.pack, unpack = ref$.unpack;
mem = new (require('FlashEEPROM'))(0x087000);
mem.endAddr = mem.addr + 1024;
out$.Config = Config;
function Config(fileNo){
  this.fNo = fileNo;
  Config.f = mem;
  this.ram = {};
}
Config.prototype.flush = function(){
  Config.f.write(this.fNo, pack(this.ram));
};
Config.prototype.read = function(){
  var e;
  try {
    merge(this.ram, unpack(E.toString(Config.f.read(this.fNo))));
    return this.ram;
  } catch (e$) {
    return e = e$;
  }
};
