// Generated by LiveScript 1.4.0
var ref$, merge, pack, unpack, mem, out$ = typeof exports != 'undefined' && exports || this;
ref$ = require('aea'), merge = ref$.merge, pack = ref$.pack, unpack = ref$.unpack;
/*
How to calculate start addres for FlashEEPROM:

http://www.espruino.com/Reference#l_Flash_getFree

require("Flash").getFree()
=[
  { "addr": 487424, "length": 4096 },
  { "addr": 524288, "length": 4096 },
  { "addr": 1011712, "length": 36864 },
  { "addr": 1048576, "length": 3129344 }
 ]
*/
mem = new (require('FlashEEPROM'))(487424);
mem.endAddr = mem.addr + 1024;
/*
mem =
    write: ->
    read: ->
*/
out$.Config = Config;
function Config(fileNo){
  this.fNo = fileNo;
  Config.f = mem;
  this.ram = {};
}
Config.prototype.flush = function(){
  Config.f.write(this.fNo, pack(this.ram));
};
Config.prototype.read = function(){
  var e;
  try {
    merge(this.ram, unpack(E.toString(Config.f.read(this.fNo))));
    return this.ram;
  } catch (e$) {
    return e = e$;
  }
};
