// Generated by LiveScript 1.4.0
var out$ = typeof exports != 'undefined' && exports || this;
out$.Led = Led;
function Led(pin){
  this.pin = pin;
  pinMode(this.pin, 'output');
  this.mode = 'turn-off';
  this.onTime = 1000;
  this.offTime = 1000;
}
Led.prototype.turn = function(val){
  this.mode = val ? 'on' : 'off';
  return digitalWrite(this.pin, val);
};
Led.prototype.baseBlink = function(){
  var self;
  self = this;
  if (this.mode !== 'blink') {
    this.mode = 'blink';
    return function lo(op){
      if (self.mode === 'blink') {
        digitalWrite(self.pin, true);
      }
      return sleep(self.onTime, function(){
        if (self.mode === 'blink') {
          digitalWrite(self.pin, false);
        }
        return sleep(self.offTime, function(){
          if (self.mode === 'blink') {
            return lo(op);
          }
          return op();
        });
      });
    }(function(){
      return console.log("blink ended, mode: ", self.mode);
    });
  }
};
Led.prototype.blink = function(){
  this.onTime = 1000;
  this.offTime = 1000;
  return this.baseBlink();
};
Led.prototype.attBlink = function(){
  this.onTime = 300;
  this.offTime = 300;
  return this.baseBlink();
};
Led.prototype.infoBlink = function(){
  this.onTime = 80;
  this.offTime = 2000;
  return this.baseBlink();
};
Led.prototype.wink = function(){
  var self;
  self = this;
  self.mode = 'wink';
  self.turn(true);
  return sleep(50, function(){
    return self.turn(false);
  });
};
